
version: '3.9'
services:
  btcturk:
    build:
      context: ./btcturk
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
      - rabbitmq
    environment:
      ASPNETCORE_URLS: "http://*:80"
      ConnectionStrings__DefaultConnection: "Server=db;Database=BtcTurk;User=sa;Password=Fuatko123;MultipleActiveResultSets=true;Integrated Security=false;TrustServerCertificate=true"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "admin"
      RabbitMQ__Password: "123456"
    networks:
      - mynetwork
    command: ["dotnet", "ef", "database update"]
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Fuatko123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - mynetwork
  rabbitmq:
    image: "rabbitmq:3.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "123456"
    networks:
      - mynetwork

volumes:
  dbdata:

networks:
  mynetwork: